### ISSUE TITLE
Googletest with Official Android NDK

### ISSUE THREAD

**Issue by famagusta** [sfuku7/googletest_android_ndk-build#3]
I was unable to use the official Android NDK - it is extremely poorly documented. 
I was able to run your example. Any issues I would face?

**Comment by famagusta** [comment]
Never mind - I figured it out. 
Just follow the googletest readme in the sources/third_party in the ndk. 
Be sure to install ndk-build (setting the correct env paths) & adb.

**Comment by sfuku7** [comment]
Fine, thank you
